[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMonoNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFontMono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"
