#!/bin/bash

# Hcloud
if ! command -v go &> /dev/null; then
  echo "Go is not installed. Please install Go and run this script again."
  exit 1
fi
go install github.com/hetznercloud/cli/cmd/hcloud@latest

go install github.com/melkeydev/go-blueprint@latest

# Kubecolor
go install github.com/kubecolor/kubecolor@latest

# k9s
go install github.com/derailed/k9s@latest

# kubens & ctx (krew)
(
  set -x
  cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  KREW="krew-${OS}_${ARCH}" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
  tar zxvf "${KREW}.tar.gz" &&
  ./"${KREW}" install krew
)

kubectl krew install ctx ns tree node-shell
