#!/bin/bash

set -e

GPG_KEY_FILE="/usr/share/keyrings/nvidia-drivers.gpg"

sudo apt install software-properties-common -y; \
sudo add-apt-repository contrib non-free-firmware -y; \
sudo add-apt-repository contrib non-free -y; \
sudo apt update

sudo apt install build-essential gcc dirmngr ca-certificates software-properties-common apt-transport-https dkms curl -y

curl -fSsL https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/3bf863cc.pub | sudo gpg --dearmor | sudo tee "$GPG_KEY_FILE" > /dev/null 2>&1; \
curl -fSsL https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/3bf863cc.pub | sudo gpg --dearmor | sudo tee -a "$GPG_KEY_FILE" > /dev/null 2>&1

echo 'deb [signed-by='"$GPG_KEY_FILE"'] https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/ /' | sudo tee /etc/apt/sources.list.d/nvidia-drivers.list > /dev/null 2>&1; \
echo 'deb [signed-by='"$GPG_KEY_FILE"'] https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/ /' | sudo tee -a /etc/apt/sources.list.d/nvidia-drivers.list > /dev/null 2>&1

sudo apt update

sudo apt install nvidia-driver cuda-drivers-550 cuda -y
